kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

# Pages configuration
name = "portfolio"
compatibility_date = "2023-06-21"
compatibility_flags = ["nodejs_compat"]
main = "workers-site/index.js"

[site]
bucket = "./build/client"
